import os

keywords = [
    "sizeof",
    "_Generic",
    "default",
    "alignof",
    "auto",
    "constexpr",
    "extern",
    "register",
    "static",
    "thread_local",
    "typedef",
    "void",
    "char",
    "short",
    "int",
    "long",
    "float",
    "double",
    "signed",
    "unsigned",
    "_BitInt",
    "bool",
    "_Complex",
    "_Decimal32",
    "_Decimal64",
    "_Decimal128",
    "struct",
    "union",
    "enum",
    "_Atomic",
    "typeof_unqual",
    "typeof",
    "const",
    "restrict",
    "volatile",
    "inline",
    "_Noreturn",
    "alignas",
    "static_assert",
    "case",
    "if",
    "else",
    "switch",
    "for",
    "while",
    "do",
    "goto",
    "continue",
    "break",
    "return",
]

with open(os.path.join(os.path.dirname(__file__), "keywords.pest"), mode="w") as file:
    print(f"keywords={{{'|'.join(map(lambda x:x.upper(),keywords))}}}", file=file)
    for keyword in keywords:
        print(f'{keyword.upper()}=@{{"{keyword}"~!identifier_continue}}', file=file)
